-- CRUD operations
-- 1. Create
-- CREATE TABLE students(
--     id  INTEGER PRIMARY KEY,
--     name TEXT,
--     age INTEGER
--     );
-- ALTER TABLE students ADD COLUMN course TEXT;
-- INSERT INTO students(name, age, course) VALUES ("Natalie" , 16 , "Computer Science");
-- INSERT INTO students(name, age, course) VALUES ("John" , 22 , "Nursing");
-- INSERT INTO students(name, age, course) VALUES ("Fortune" , 10 , "Commerce");
-- INSERT INTO students(name, age, course) VALUES ("Abiud" , 20 , "Finance");

-- 2. Retrieve
-- SELECT * FROM students;
-- SELECT name, age FROM students;
-- SELECT id, name FROM students;
-- SELECT DISTINCT name FROM  students;
-- SELECT * FROM students WHERE age > 18;
-- 3. Update
-- UPDATE students SET name = "Linda" WHERE name = "Fortune";
-- 4. Delete
-- DELETE FROM students WHERE id =3;
-- DROP TABLE students

